CourseSelSystem/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from CourseSelSystem import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('base.urls', 'base'), namespace='base')),
    path('student/', include(('student.urls', 'student'), namespace='student')),
    path('classes/', include(('classes.urls', 'classes'), namespace='classes')),
    path('course/', include(('course.urls', 'course'), namespace='course')),
    path('teacher/', include(('teacher.urls', 'teacher'), namespace='teacher')),
    #定义基本的应用

    re_path(r'^media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),

]

base/urls.py
from django.urls import path
from base import views

urlpatterns = [
    path('', views.index, name='index'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('register/', views.register, name='register'),
    path('get_auth_code/', views.get_auth_code, name='get_auth_code'),

    path('edit_avatar/', views.edit_avatar, name='edit_avatar'),
    path('edit_password/', views.edit_password, name='edit_password'),

    path('students/', views.students, name='students'),
    path('classes/', views.classes, name='classes'),
    path('course/', views.course, name='course'),
    path('teacher/', views.teacher, name='teacher'),
    #可视化
    path("canlook/",views.CanLook,name='canLook'),
    path("canlook/get/",views.GetData,name='data')

]

student/urls.py
from django.urls import path
from student import views

urlpatterns = [
    path('add/', views.add, name='add'),
    path('edit/<int:current_pk>', views.edit, name='edit'),
    path('dels/', views.dels, name='dels'),
    path('search/', views.search, name='search'),
    path('import_student/', views.import_student, name='import_student'),

]

student/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

import os


def user_directory_path(instance, filename):
    return os.path.join('user_dir_path', instance.username, "avatars", filename)


class UserInfo(AbstractUser):
    avatar = models.ImageField(upload_to=user_directory_path, default='/static/images/default.png')
    student = models.OneToOneField(to='Student', on_delete=models.CASCADE)

    class Meta:
        db_table = "db_userinfo"

    def __str__(self):
        return self.username


class Student(models.Model):
    name = models.CharField(max_length=32, verbose_name='学生姓名')
    age = models.SmallIntegerField(default=18, verbose_name='学生年龄')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    student_detail = models.OneToOneField(to='StudentDetail', on_delete=models.CASCADE, null=True, blank=True)
    classes = models.ForeignKey(to='Classes', on_delete=models.CASCADE, related_name='classes', null=True, blank=True)
    course = models.ManyToManyField(
        to='Course',
        through='Student2Course',
        through_fields=('student', 'course'),
        related_name='student_course',
    )

    class Meta:
        db_table = "db_student"

    def __str__(self):
        return self.name


class Classes(models.Model):
    name = models.CharField(max_length=32, verbose_name='班级名称')

    class Meta:
        db_table = "db_classes"

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=32, verbose_name='课程名称')
    credit = models.SmallIntegerField(default=3, verbose_name='课程学分')
    course_open_time = models.DateField(auto_now=True, verbose_name='开课时间')

    teacher = models.ForeignKey(to='Teacher', on_delete=models.CASCADE, related_name='teacher', null=True, blank=True)

    class Meta:
        db_table = "db_course"

    def __str__(self):
        return self.name


class Teacher(models.Model):
    name = models.CharField(max_length=32, verbose_name='老师姓名')
    phone = models.CharField(max_length=11, null=True, blank=True, verbose_name='老师手机号')

    class Meta:
        db_table = "db_teacher"

    def __str__(self):
        return self.name


class StudentDetail(models.Model):
    gender_choice = (
        (0, '保密'),
        (1, '男'),
        (2, '女'),
    )
    gender = models.SmallIntegerField(choices=gender_choice, default=0, verbose_name='性别')
    addr = models.CharField(max_length=64, null=True, blank=True, verbose_name='地址详情')
    phone = models.CharField(max_length=11, null=True, blank=True, verbose_name='手机号')

    class Meta:
        db_table = "db_student_detail"


class Student2Course(models.Model):
    student = models.ForeignKey(to='Student', on_delete=models.CASCADE)
    course = models.ForeignKey(to='Course', on_delete=models.CASCADE)
    choice_course_time = models.DateTimeField(auto_now_add=True, verbose_name='学生选课时间')

    class Meta:
        db_table = "db_student2course"

student/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.db import transaction
from django.http import JsonResponse
from student import models

from openpyxl import load_workbook

from utils.res import ResponseData


def add(request):
    class_queryset = models.Classes.objects.all()
    course_queryset = models.Course.objects.all()
    tem_dict = {'class_queryset': class_queryset, 'course_queryset': course_queryset}

    if request.method == 'POST':
        name = request.POST.get('name')
        age = request.POST.get('age')
        classes_id = request.POST.get('classes')
        course_id_list = request.POST.getlist('course')
        if not age:
            age = 18
        try:
            with transaction.atomic():
                stu_obj = models.Student.objects.create(name=name, age=age, classes_id=classes_id)
                course_list = []
                for course_id in course_id_list:
                    course_list.append(models.Student2Course(student=stu_obj, course_id=course_id))
                models.Student2Course.objects.bulk_create(course_list)
        except Exception as e:
            print(e)
            print('服务器错误---student/add!')
        finally:
            return redirect('base:students')

    return render(request, 'student/add.html', tem_dict)

class ResponseData:
    def __init__(self, status=0, message=''):
        self.status = status
        self.message = message

    def get_dict(self):
        return {'status': self.status, 'message': self.message}

def dels(request):
    res_dict = ResponseData()
    current_pk = request.POST.get('current_pk')
    if current_pk:
        try:
            with transaction.atomic():
                stu_obj = models.Student.objects.select_for_update().get(pk=current_pk)
                # 假设您需要在这里执行一些删除操作
                stu_obj.delete()
                res_dict.status = 2000
                res_dict.message = 'Student deleted successfully.'
        except models.Student.DoesNotExist:
            res_dict.status = 4001
            res_dict.message = 'Student not found.'
        except Exception as e:
            res_dict.status = 5000
            res_dict.message = 'Server error.'
            print(e)
    else:
        res_dict.status = 4000
        res_dict.message = 'Invalid request.'

    return JsonResponse(res_dict.get_dict())


def edit(request, current_pk):
    stu_obj = models.Student.objects.filter(pk=current_pk).first()
    class_queryset = models.Classes.objects.all()
    course_queryset = models.Course.objects.all()
    course_id_list = [course.pk for course in stu_obj.course.all()]
    tem_dict = {
        'stu_obj': stu_obj,
        'class_queryset': class_queryset,
        'course_queryset': course_queryset,
        'course_id_list': course_id_list
    }
    if request.method == 'POST':
        name = request.POST.get('name')
        age = request.POST.get('age')
        classes_id = request.POST.get('classes')
        course_id_list = request.POST.getlist('course')
        try:
            with transaction.atomic():
                models.Student.objects.filter(pk=current_pk).update(name=name, age=age, classes_id=classes_id)
                models.Student2Course.objects.filter(student=stu_obj).delete()
                course_list = []
                for course_id in course_id_list:
                    course_list.append(models.Student2Course(student=stu_obj, course_id=course_id))
                models.Student2Course.objects.bulk_create(course_list)
        except Exception as e:
            print(e)
            print('服务器错误---student/edit!')
        finally:
            return redirect('base:students')
    return render(request, 'student/edit.html', tem_dict)


def search(request):
    if request.method == 'POST':
        category = request.POST.get('category')
        key_word = request.POST.get('key_word')
        if category == 'name':
            ret_queryset = models.Student.objects.filter(name__contains=key_word)
        elif category == 'classes':
            ret_queryset = models.Student.objects.filter(classes__name__contains=key_word)
        elif category == 'course':
            ret_queryset = models.Student.objects.filter(course__name=key_word)
        else:
            ret_queryset = None
        return render(request, 'student/search.html', {'ret_queryset': ret_queryset, 'key_word': key_word})


def import_student(request):
    if request.method == 'POST':
        import_file = request.FILES.get('import_file')
        if not import_file:
            return HttpResponse('请先选择文件')
        wb = load_workbook(import_file)
        sheet = wb.worksheets[0]
        gender_dict = {
            '保密': 0,
            '男': 1,
            '女': 2,
        }
        for cells in sheet.iter_rows():
            name = cells[0].value or None
            if name == '姓名':
                continue
            gender = cells[1].value
            gender_val = gender_dict.get(gender, 0)
            age = cells[2].value or None
            addr = cells[3].value or None
            phone = cells[4].value or None
            classes_name = cells[5].value or None
            try:
                with transaction.atomic():
                    class_obj = models.Classes.objects.filter(name=classes_name).first()
                    student_detail_obj = models.StudentDetail.objects.create(gender=gender_val, addr=addr, phone=phone)
                    models.Student.objects.create(name=name, age=age, classes=class_obj,
                                                  student_detail=student_detail_obj)
            except Exception as e:
                print(e)
                print('服务器错误---student/import_student!')
        return redirect('base:students')

templates/student/add.html
{% extends 'base/index.html' %}

{% block title %}
    <title>student-add</title>
{% endblock title %}

{% block content %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="panel-title">添加</div>
        </div>
        <div class="panel-body">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name">姓名: </label>
                    <input type="text" id="id_name" name="name" class="form-control">
                </div>
                <div class="form-group">
                    <label for="id_age">年龄: </label>
                    <input type="text" id="id_age" name="age" class="form-control">
                </div>
                <div class="form-group">
                    {% for class_obj in class_queryset %}
                        <label for="id_classes_{{ forloop.counter }}">{{ class_obj.name }}</label>
                        <input type="radio" id="id_classes_{{ forloop.counter }}" name="classes" value="{{ class_obj.pk }}">
                    {% endfor %}
                </div>
                <div class="form-group">
                    {% for course_obj in course_queryset %}
                        <label for="id_course_{{ forloop.counter }}">{{ course_obj.name }}</label>
                        <input type="checkbox" id="id_course_{{ forloop.counter }}" name="course" value="{{ course_obj.pk }}">
                    {% endfor %}
                </div>
                <input type="submit" class="btn btn-danger" value="确认添加">
                <a href="{% url 'base:students' %}" class="btn btn-primary">取消添加</a>
            </form>
        </div>
    </div>
{% endblock content %}

templates/student/edit.html
{% extends 'base/index.html' %}

{% block title %}
    <title>student-edit</title>
{% endblock title %}

{% block content %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="panel-title">修改</div>
        </div>
        <div class="panel-body">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name">姓名: </label>
                    <input type="text" id="id_name" name="name" value="{{ stu_obj.name }}" class="form-control">
                </div>
                <div class="form-group">
                    <label for="id_age">年龄: </label>
                    <input type="text" id="id_age" name="age" value="{{ stu_obj.age }}" class="form-control">
                </div>
                <div class="form-group">
                    {% for class_obj in class_queryset %}
                        {% if stu_obj.classes_id == class_obj.pk %}
                            <label for="id_classes_{{ forloop.counter }}">{{ class_obj.name }}</label>
                            <input type="radio" id="id_classes_{{ forloop.counter }}" name="classes"
                                   value="{{ class_obj.pk }}" checked>
                        {% else %}
                            <label for="id_classes_{{ forloop.counter }}">{{ class_obj.name }}</label>
                            <input type="radio" id="id_classes_{{ forloop.counter }}" name="classes"
                                   value="{{ class_obj.pk }}">
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="form-group">
                    {% for course_obj in course_queryset %}
                        {% if forloop.counter in course_id_list %}
                            <label for="id_course_{{ forloop.counter }}">{{ course_obj.name }}</label>
                            <input type="checkbox" id="id_course_{{ forloop.counter }}" name="course"
                                   value="{{ course_obj.pk }}" checked>
                        {% else %}
                            <label for="id_course_{{ forloop.counter }}">{{ course_obj.name }}</label>
                            <input type="checkbox" id="id_course_{{ forloop.counter }}" name="course"
                                   value="{{ course_obj.pk }}">
                        {% endif %}
                    {% endfor %}
                </div>
                <input type="submit" class="btn btn-danger" value="确认修改">
                <a href="{% url 'base:students' %}" class="btn btn-primary">取消修改</a>
            </form>
        </div>
    </div>
{% endblock content %}

templates/student/search.html
{% extends 'base/index.html' %}

{% block title %}
    <title>students</title>
{% endblock title %}

{% block content %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="panel-title">查询结果</div>
        </div>
        <div class="panel-body">
            <div class="row">
                <a href="{% url 'base:students' %}" class="btn btn-success btn-sm">返回</a>
                <table class="table table-hover table-striped text-center">
                    <thead>
                    <tr>
                        <th class="text-center">序号</th>
                        <th class="text-center">姓名</th>
                        <th class="text-center">年龄</th>
                        <th class="text-center">班级</th>
                        <th class="text-center">所选课程</th>
                        <th class="text-center">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for student_obj in ret_queryset %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ student_obj.name }}</td>
                            <td>{{ student_obj.age }}</td>
                            <td>{{ student_obj.classes.name }}</td>
                            <td>
                                {% for course_obj in student_obj.course.all %}
                                    {% if forloop.last %}
                                        {{ course_obj.name }}
                                    {% else %}
                                        {{ course_obj.name }},
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td>
                                <a href="{% url 'student:edit' student_obj.pk %}" class="btn btn-primary btn-sm">修改</a>
                                <button current_pk="{{ student_obj.pk }}" class="del_btn btn btn-danger btn-sm">删除
                                </button>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script>
        $('.del_btn').click(function () {
            let $that = $(this);
            $.ajax({
                url: '{% url "student:dels" %}',
                type: 'post',
                data: {
                    'current_pk': $(this).attr('current_pk'),
                },
                success: function (res) {
                    if (res.status === 2000) {
                        $that.parent().parent().remove();
                    } else {
                        window.location.reload();
                    }
                }
            })
        })
    </script>
{% endblock js %}