CourseSelSystem/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from CourseSelSystem import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('base.urls', 'base'), namespace='base')),
    path('student/', include(('student.urls', 'student'), namespace='student')),
    path('classes/', include(('classes.urls', 'classes'), namespace='classes')),
    path('course/', include(('course.urls', 'course'), namespace='course')),
    path('teacher/', include(('teacher.urls', 'teacher'), namespace='teacher')),
    #定义基本的应用

    re_path(r'^media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),

]

base/urls.py
from django.urls import path
from base import views

urlpatterns = [
    path('', views.index, name='index'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('register/', views.register, name='register'),
    path('get_auth_code/', views.get_auth_code, name='get_auth_code'),

    path('edit_avatar/', views.edit_avatar, name='edit_avatar'),
    path('edit_password/', views.edit_password, name='edit_password'),

    path('students/', views.students, name='students'),
    path('classes/', views.classes, name='classes'),
    path('course/', views.course, name='course'),
    path('teacher/', views.teacher, name='teacher'),
    #可视化
    path("canlook/",views.CanLook,name='canLook'),
    path("canlook/get/",views.GetData,name='data')

]

course/urls.py
from django.urls import path
from course import views

urlpatterns = [
    path('add/', views.add, name='add'),
    path('edit/<int:current_pk>', views.edit, name='edit'),
    path('dels/', views.dels, name='dels'),
]

student/urls.py
from django.urls import path
from student import views

urlpatterns = [
    path('add/', views.add, name='add'),
    path('edit/<int:current_pk>', views.edit, name='edit'),
    path('dels/', views.dels, name='dels'),
    path('search/', views.search, name='search'),
    path('import_student/', views.import_student, name='import_student'),

]

teacher/urls.py
from django.urls import path
from teacher import views

urlpatterns = [
    path('add/', views.add, name='add'),
    path('edit/<int:current_pk>', views.edit, name='edit'),
    path('dels/', views.dels, name='dels'),

]

base/models.py
from django.db import models

# Create your models here.

course/models.py
from django.db import models

# Create your models here.

student/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

import os


def user_directory_path(instance, filename):
    return os.path.join('user_dir_path', instance.username, "avatars", filename)


class UserInfo(AbstractUser):
    avatar = models.ImageField(upload_to=user_directory_path, default='/static/images/default.png')
    student = models.OneToOneField(to='Student', on_delete=models.CASCADE)

    class Meta:
        db_table = "db_userinfo"

    def __str__(self):
        return self.username


class Student(models.Model):
    name = models.CharField(max_length=32, verbose_name='学生姓名')
    age = models.SmallIntegerField(default=18, verbose_name='学生年龄')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    student_detail = models.OneToOneField(to='StudentDetail', on_delete=models.CASCADE, null=True, blank=True)
    classes = models.ForeignKey(to='Classes', on_delete=models.CASCADE, related_name='classes', null=True, blank=True)
    course = models.ManyToManyField(
        to='Course',
        through='Student2Course',
        through_fields=('student', 'course'),
        related_name='student_course',
    )

    class Meta:
        db_table = "db_student"

    def __str__(self):
        return self.name


class Classes(models.Model):
    name = models.CharField(max_length=32, verbose_name='班级名称')

    class Meta:
        db_table = "db_classes"

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=32, verbose_name='课程名称')
    credit = models.SmallIntegerField(default=3, verbose_name='课程学分')
    course_open_time = models.DateField(auto_now=True, verbose_name='开课时间')

    teacher = models.ForeignKey(to='Teacher', on_delete=models.CASCADE, related_name='teacher', null=True, blank=True)

    class Meta:
        db_table = "db_course"

    def __str__(self):
        return self.name


class Teacher(models.Model):
    name = models.CharField(max_length=32, verbose_name='老师姓名')
    phone = models.CharField(max_length=11, null=True, blank=True, verbose_name='老师手机号')

    class Meta:
        db_table = "db_teacher"

    def __str__(self):
        return self.name


class StudentDetail(models.Model):
    gender_choice = (
        (0, '保密'),
        (1, '男'),
        (2, '女'),
    )
    gender = models.SmallIntegerField(choices=gender_choice, default=0, verbose_name='性别')
    addr = models.CharField(max_length=64, null=True, blank=True, verbose_name='地址详情')
    phone = models.CharField(max_length=11, null=True, blank=True, verbose_name='手机号')

    class Meta:
        db_table = "db_student_detail"


class Student2Course(models.Model):
    student = models.ForeignKey(to='Student', on_delete=models.CASCADE)
    course = models.ForeignKey(to='Course', on_delete=models.CASCADE)
    choice_course_time = models.DateTimeField(auto_now_add=True, verbose_name='学生选课时间')

    class Meta:
        db_table = "db_student2course"

teacher/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render, HttpResponse, redirect
from PIL import Image, ImageDraw, ImageFont

from io import BytesIO
import random

import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import LabelEncoder

from base.reg_forms import RegForm
from student import models
from utils.res import ResponseData
from django.http import JsonResponse
from django.contrib import auth
from django.db import transaction
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from collections import Counter


def is_ajax(request):
    return request.headers.get('X-Requested-With') == 'XMLHttpRequest'

def index(request):
    return render(request, 'base/index.html', locals())


def signin(request):
    if is_ajax(request):
        if request.method == 'POST':
            res_dict = ResponseData()
            session_code = request.session.get('auth_code')
            auth_code = request.POST.get('auth_code')
            if auth_code.upper() != session_code.upper():
                res_dict.status = 4000
                res_dict.message = '验证码输入不正确!'
                return JsonResponse(res_dict.get_dict)
            username = request.POST.get('username')
            password = request.POST.get('password')
            user_obj = auth.authenticate(request, username=username, password=password)
            if user_obj:
                auth.login(request, user_obj)
                res_dict.message = '登录成功!'
            else:
                res_dict.status = 4000
                res_dict.message = '用户名或密码输入不正确!'
            return JsonResponse(res_dict.get_dict)
    return render(request, 'base/signin.html')


def signout(request):
    auth.logout(request)
    return redirect('base:index')


def register(request):
    form_obj = RegForm()
    if is_ajax(request):
        if request.method == 'POST':
            res_dict = ResponseData()
            form_obj = RegForm(request.POST)
            if form_obj.is_valid():
                clean_data = form_obj.cleaned_data
                clean_data.pop('confirm_password')
                avatar = request.FILES.get('avatar')
                if avatar:
                    clean_data['avatar'] = avatar
                username = clean_data.get('username')
                try:
                    with transaction.atomic():
                        stu_obj = models.Student.objects.create(name=username)
                        models.UserInfo.objects.create_user(**clean_data, student=stu_obj)
                except Exception as e:
                    print(e)
                    print('服务器错误---register!')
            else:
                error_data = form_obj.errors
                res_dict.status = 4000
                res_dict.message = '数据检验失败!'
                res_dict.data = error_data
            return JsonResponse(res_dict.get_dict)

    return render(request, 'base/register.html', {'form_obj': form_obj})


def get_auth_code(request, size=(450, 35), mode="RGB", bg_color=(255, 255, 255)):
    """ 生成一个图片验证码 """
    _letter_cases = "abcdefghjkmnpqrstuvwxy"  # 小写字母，去除可能干扰的i，l，o，z
    _upper_cases = _letter_cases.upper()  # 大写字母
    _numbers = ''.join(map(str, range(3, 10)))  # 数字
    chars = ''.join((_letter_cases, _upper_cases, _numbers))

    width, height = size  # 宽高
    # 创建图形
    img = Image.new(mode, size, bg_color)
    draw = ImageDraw.Draw(img)  # 创建画笔

    def get_chars():
        """生成给定长度的字符串，返回列表格式"""
        return random.sample(chars, 4)

    def create_lines():
        """绘制干扰线"""
        line_num = random.randint(*(1, 2))  # 干扰线条数

        for i in range(line_num):
            # 起始点
            begin = (random.randint(0, size[0]), random.randint(0, size[1]))
            # 结束点
            end = (random.randint(0, size[0]), random.randint(0, size[1]))
            draw.line([begin, end], fill=(0, 0, 0))

    def create_points():
        """绘制干扰点"""
        chance = min(100, max(0, int(2)))  # 大小限制在[0, 100]

        for w in range(width):
            for h in range(height):
                tmp = random.randint(0, 100)
                if tmp > 100 - chance:
                    draw.point((w, h), fill=(0, 0, 0))

    def create_code():
        """绘制验证码字符"""
        char_list = get_chars()
        code_string = ''.join(char_list)  # 每个字符前后以空格隔开

        for i in range(len(char_list)):
            code_str = char_list[i]
            font = ImageFont.truetype('media/static/font/Rondal-Semibold.ttf', size=24)
            draw.text(((i + 1) * 75, 0), code_str, "red", font=font)

        return code_string

    create_lines()
    create_points()
    code = create_code()
    print(code)

    request.session['auth_code'] = code

    io_obj = BytesIO()
    img.save(io_obj, 'PNG')
    return HttpResponse(io_obj.getvalue())


def edit_avatar(request):
    if request.method == 'POST':
        new_avatar = request.FILES.get('new_avatar')
        if new_avatar:
            request.user.avatar = new_avatar
            request.user.save()
        return redirect('base:index')


def edit_password(request):
    if request.method == 'POST':
        old_password = request.POST.get('old_password')
        new_password = request.POST.get('new_password')
        is_right = request.user.check_password(old_password)
        if is_right:
            request.user.set_password(new_password)
            request.user.save()
            return redirect('base:signin')
        return HttpResponse('原密码错误!')


def students(request):
    student_queryset = models.Student.objects.all()
    paginator = Paginator(student_queryset, 5)  # 修改每页显示为5个学生
    total_pages = paginator.num_pages  # 不需要减1了
    current_page = request.GET.get('page', 1)
    current_page = int(current_page)
    
    # 验证当前页码是否在有效范围内
    if current_page < 1 or current_page > paginator.num_pages:
        current_page = 1
    
    previous_page = current_page - 1
    next_page = current_page + 1
    
    # 简化页码范围逻辑
    page_ranges = range(max(1, current_page - 2), min(paginator.num_pages, current_page + 3))
    
    stu_list = paginator.page(current_page)
    tem_dict = {
        'student_queryset': student_queryset,
        'paginator': paginator,
        'current_page': current_page,
        'total_pages': total_pages,
        'page_ranges': page_ranges,
        'stu_list': stu_list,
    }
    return render(request, 'base/students.html', tem_dict)


def classes(request):
    class_queryset = models.Classes.objects.all()
    return render(request, 'base/classes.html', locals())


def course(request):
    course_queryset = models.Course.objects.all()
    return render(request, 'base/course.html', locals())


def teacher(request):
    teacher_queryset = models.Teacher.objects.all()
    return render(request, 'base/teacher.html', locals())

def CanLook(request):
    return render(request,'CanLook.html',locals())

def GetData(request):
    course_queryset = models.Course.objects.all()
    course_names = list(models.Course.objects.all().values_list('name', flat=True))
    class_names = list(models.Classes.objects.all().values_list('name', flat=True))
    course_ids = list(models.Student2Course.objects.all().values_list("course_id",flat=True))
    #print(course_names)
    #print(class_names)
    #热力图数据
    course_student_pairs = list(models.Student2Course.objects.all().values_list("course_id", "student_id", flat=False))
    #print(course_student_pairs)
    # 使用Counter统计每个course_id出现的次数
   # 提取课程ID和学生ID
    course_ids = [pair[0] for pair in course_student_pairs]
    student_ids = [pair[1] for pair in course_student_pairs]

    # 使用 Counter 统计每个课程的选课人数
    course_counts = Counter(course_ids)

    #折线图数据
    courseSelectTime=[]
    courseChineseName = []

    # 输出每个课程的选课人数
    for course_id, count in course_counts.items():
        print(f"课程 {course_id} 被选了 {count} 次。")
        courseChineseName.append(course_names[course_id-1])
        courseSelectTime.append(count)

    #print(courseChineseName)
    #print(courseSelectTime)


    class_student_pairs = list(models.Student.objects.all().values_list("id", "classes", flat=False))
    #print(class_student_pairs)

    result = []
    #将学号换为班级号，用于统计
    for i in course_student_pairs:
        for j in class_student_pairs:
            if(i[1]==j[0]):
                result.append((i[0],j[1]))
    
    # print(result)
    # print(course_names)
    # print(class_names)

    XData,YData,ResultMap = returnHotData(result,course_names,class_names)
    #print(XData)
    # print(YData)
    # print(ResultMap)


    course_id_counts = Counter(course_ids)
    
    # 将统计结果转换为列表或其他所需格式
    course_id_counts_list = list(course_id_counts.items())
    
    courseNameNum = []
    courseNameCount = []
    for i in course_id_counts_list:
        courseNameNum.append(i[0])
        courseNameCount.append(i[1])
    
    courseNameString = []
    for i in courseNameNum:
        courseNameString.append(course_names[i-1])
    
    # 使用列表推导式将courseNameCount和courseNameString转换成所需的格式
    formatted_data = [
    {"value": count, "name": name}
    for count, name in zip(courseNameCount, courseNameString)
    ]
    
    #print(formatted_data)
    #print(course_names)
    #resultForest =  randomForest()

    #print(resultForest)

    

    return JsonResponse({"data":courseNameCount,
                         "courseName":courseNameString,
                         #柱状图
                         
                         #饼图
                         "pieData":formatted_data,
                         #热力图
                         "XData":class_names,
                         "YData":course_names,
                         "resultMap":ResultMap,
                         #折线图
                         "courseSelectTime":courseSelectTime,

teacher/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.http import JsonResponse
from django.db import transaction

from student import models
from utils.res import ResponseData


def add(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        try:
            with transaction.atomic():
                models.Teacher.objects.create(name=name, phone=phone)
        except Exception as e:
            print(e)
            print('服务器错误---teacher/add!')
        finally:
            return redirect('base:teacher')

    return render(request, 'teacher/add.html')


def edit(request, current_pk):
    teacher_obj = models.Teacher.objects.filter(pk=current_pk).first()
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        models.Teacher.objects.filter(pk=current_pk).update(name=name, phone=phone)
        return redirect('base:teacher')
    return render(request, 'teacher/edit.html', {'teacher_obj': teacher_obj})

def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

def dels(request):
    if is_ajax(request):
        if request.method == 'POST':
            res_dict = ResponseData()
            current_pk = request.POST.get('current_pk')
            try:
                models.Teacher.objects.filter(pk=current_pk).delete()
            except Exception as e:
                res_dict.status = 5000
                res_dict.message = '服务器错误---teacher/dels!'
                print(e)
                print(res_dict.message)
            finally:
                return JsonResponse(res_dict.get_dict)

templates/base/classes.html
{% extends 'base/index.html' %}

{% block title %}
    <title>classes</title>
{% endblock title %}

{% block content %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="panel-title">班级管理</div>
        </div>
        <div class="panel-body">
            <table class="table table-hover table-striped text-center">
                <thead>
                <tr>
                    <th class="text-center">序号</th>
                    <th class="text-center">姓名</th>
                </tr>
                </thead>
                <tbody>
                {% for class_obj in class_queryset %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ class_obj.name }}</td>
                        <td>
                            <a href="{% url 'classes:edit' class_obj.pk %}" class="btn btn-primary btn-sm">修改</a>
                            <button current_pk="{{ class_obj.pk }}" class="del_btn btn btn-danger btn-sm">删除</button>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <a href="{% url 'classes:add' %}" class="add_btn btn btn-success pull-right">添加</a>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script>
        $('.del_btn').click(function () {
            let $that = $(this);
            $.ajax({
                url: '{% url "classes:dels" %}',
                type: 'post',
                data: {
                    'current_pk': $(this).attr('current_pk'),
                },
                success: function (res) {
                    if (res.status === 2000) {
                        $that.parent().parent().remove();
                    } else {
                        window.location.reload();
                    }
                }
            })
        })
    </script>
{% endblock js %}

templates/base/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>index</title>
    {% endblock title %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap-3.4.1-dist/css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'js/csrf_token.js' %}"></script>
    <script src="{% static 'bootstrap-3.4.1-dist/js/bootstrap.min.js' %}"></script>
    <style>
        #user_avatar {
            width: 30px;
            height: 30px;
            border-radius: 50%;
        }

        #old_avatar, #new_avatar {
            width: 100px;
            height: 100px;
            border-radius: 50%;
            margin-left: 20px;
        }

        /* 全局字体和背景颜色 */
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f8f9fa;
            color: #333;
        }

        /* 导航栏样式 */
        .navbar {
            background-color: #fff;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            border-bottom: 1px solid #eee;
        }

        .navbar-brand {
            font-weight: bold;
            color: #d9534f;
        }

        /* 面板样式 */
        .panel {
            border: none;
            border-radius: 0;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .panel-heading {
            background-color: #f5f5f5;
            border-bottom: 1px solid #eee;
        }

        .panel-body {
            padding: 20px;
        }

        .panel-title {
            font-size: 1.5em;
            color: #333;
        }

        /* 导航栏链接样式 */
        .nav a {
            color: #555;
            font-weight: bold;
        }

        .nav .active a {
            color: #d9534f;
        }

        /* 模态框样式 */
        .modal-content {
            border-radius: 0;
            border: none;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        /* 表单样式 */
        .form-group {
            margin-bottom: 20px;
        }

        label {
            font-weight: normal;
        }

        input[type="password"],
        input[type="file"] {
            border-radius: 0;
            box-shadow: none;
            border-color: #ccc;
        }

        /* 按钮样式 */
        .btn {
            border-radius: 0;
        }

        .btn-primary {
            background-color: #d9534f;
            border-color: #d9534f;
        }

        .btn-default {
            background-color: #fff;
            border-color: #ccc;
        }

        /* 其他样式 */
        .dropdown-menu {
            border-radius: 0;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        .dropdown-menu > li > a {
            color: #333;
        }

        .dropdown-menu > li > a:hover {
            background-color: #e0e0e0;
        }

        /* 导航栏下拉菜单样式 */
        .navbar .dropdown-menu {
            background-color: #fff;
        }

        .navbar .dropdown-menu > li > a {
            padding: 10px 20px;
        }

        /* 用户头像样式 */
        #user_avatar {
            margin-right: 10px;
        }

        
    </style>
    {% block css %}

    {% endblock css %}
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'base:index' %}">选课系统</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                {% if request.path == '/' %}
                    <li class="active"><a href="{% url 'base:index' %}">首页 <span class="sr-only">(current)</span></a>
                    </li>
                {% else %}
                    <li><a href="{% url 'base:index' %}">首页</a></li>
                {% endif %}
                
            </ul>
            {% if request.user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'base:index' %}">{{ request.user.username }}</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">
                            <img id="user_avatar" src="/media/{{ request.user.avatar }}" alt="用户头像">
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#" data-toggle="modal" data-target="#edit_avatar" data-whatever="@mdo">
                                修改头像
                            </a></li>
                            <li><a href="#" data-toggle="modal" data-target="#edit_password"
                                   data-whatever="@mdo">修改密码</a></li>

                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'base:signout' %}">注销</a></li>
                        </ul>
                    </li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'base:signin' %}">登录</a></li>
                    <li><a href="{% url 'base:register' %}">注册</a></li>
                </ul>
            {% endif %}

        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">
    <div class="row">
        <!-- 左边导航栏 -->
        <div class="col-md-2">
            <div class="panel panel-default">
                <a href="{% url 'base:index' %}">
                    <div class="panel-body">首页</div>
                </a>
                <a href="{% url 'base:students' %}">
                    <div class="panel-footer">学生管理</div>
                </a>
                <a href="{% url 'base:classes' %}">
                    <div class="panel-footer">班级管理</div>
                </a>
                <a href="{% url 'base:course' %}">
                    <div class="panel-footer">课程管理</div>
                </a>
                <a href="{% url 'base:teacher' %}">
                    <div class="panel-footer">老师管理</div>
                </a>
                <a href="{% url 'base:canLook' %}">
                    <div class="panel-footer">可视化图表</div>
                </a>
            </div>
        </div>
        <!-- 右边内容 -->
        <div class="col-md-10">
            {% block content %}
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="panel-title">首页</div>
                    </div>
                    <div class="panel-body">
                        <h4>欢迎进入选课系统</h4>
                        {% if request.user.last_login %}
                            <p>上一次登录：{{ request.user.last_login|date:'Y-m-d H:i:s' }}</p>
                        {% endif %}
                        <p>管理员：hkwJsxl@gmail.com</p>
                        <p>项目地址：<a href="https://github.com/HkwJsxl/CourseSelSystem" target="_blank">https://github.com/HkwJsxl/CourseSelSystem</a>
                        </p>
                    </div>
                </div>
            {% endblock content %}
        </div>
    </div>
</div>

<div class="modal fade" id="edit_avatar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="exampleModalLabel">修改头像</h4>
            </div>
            <div class="modal-body">
                <form action="{% url 'base:edit_avatar' %}" method="post" enctype="multipart/form-data" novalidate>
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="old_avatar">原头像:</label>
                        <img src="/media/{{ request.user.avatar }}" alt="用户原头像" id="old_avatar">
                    </div>
                    <div class="form-group">
                        <label for="new_avatar_input">
                            新头像:<img src="/media/{{ request.user.avatar }}" alt="用户原头像" id="new_avatar">
                        </label>
                        <input type="file" id="new_avatar_input" name="new_avatar" class="hide">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="edit_password" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="exampleModalLabel">修改密码</h4>
            </div>
            <div class="modal-body">
                <form action="{% url 'base:edit_password' %}" method="post" enctype="multipart/form-data" novalidate>
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="old_password">原密码:</label>
                        <input type="password" name="old_password" id="old_password" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="new_password">新密码:</label>
                        <input type="password" name="new_password" id="new_password" class="form-control">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<script>
    $('#new_avatar_input').change(function () {
        let myFileReaderObj = new FileReader();
        let fileObj = $(this)[0].files[0];
        myFileReaderObj.readAsDataURL(fileObj)
        myFileReaderObj.onload = function () {
            $('#new_avatar').attr('src', myFileReaderObj.result)
        }
    })
</script>
{% block js %}

{% endblock js %}
</body>
</html>