CourseSelSystem/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from CourseSelSystem import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('base.urls', 'base'), namespace='base')),
    path('student/', include(('student.urls', 'student'), namespace='student')),
    path('classes/', include(('classes.urls', 'classes'), namespace='classes')),
    path('course/', include(('course.urls', 'course'), namespace='course')),
    path('teacher/', include(('teacher.urls', 'teacher'), namespace='teacher')),
    #定义基本的应用

    re_path(r'^media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),

]

base/urls.py
from django.urls import path
from base import views

urlpatterns = [
    path('', views.index, name='index'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('register/', views.register, name='register'),
    path('get_auth_code/', views.get_auth_code, name='get_auth_code'),

    path('edit_avatar/', views.edit_avatar, name='edit_avatar'),
    path('edit_password/', views.edit_password, name='edit_password'),

    path('students/', views.students, name='students'),
    path('classes/', views.classes, name='classes'),
    path('course/', views.course, name='course'),
    path('teacher/', views.teacher, name='teacher'),
    #可视化
    path("canlook/",views.CanLook,name='canLook'),
    path("canlook/get/",views.GetData,name='data')

]

teacher/urls.py
from django.urls import path
from teacher import views

urlpatterns = [
    path('add/', views.add, name='add'),
    path('edit/<int:current_pk>', views.edit, name='edit'),
    path('dels/', views.dels, name='dels'),

]

student/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

import os


def user_directory_path(instance, filename):
    return os.path.join('user_dir_path', instance.username, "avatars", filename)


class UserInfo(AbstractUser):
    avatar = models.ImageField(upload_to=user_directory_path, default='/static/images/default.png')
    student = models.OneToOneField(to='Student', on_delete=models.CASCADE)

    class Meta:
        db_table = "db_userinfo"

    def __str__(self):
        return self.username


class Student(models.Model):
    name = models.CharField(max_length=32, verbose_name='学生姓名')
    age = models.SmallIntegerField(default=18, verbose_name='学生年龄')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    student_detail = models.OneToOneField(to='StudentDetail', on_delete=models.CASCADE, null=True, blank=True)
    classes = models.ForeignKey(to='Classes', on_delete=models.CASCADE, related_name='classes', null=True, blank=True)
    course = models.ManyToManyField(
        to='Course',
        through='Student2Course',
        through_fields=('student', 'course'),
        related_name='student_course',
    )

    class Meta:
        db_table = "db_student"

    def __str__(self):
        return self.name


class Classes(models.Model):
    name = models.CharField(max_length=32, verbose_name='班级名称')

    class Meta:
        db_table = "db_classes"

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=32, verbose_name='课程名称')
    credit = models.SmallIntegerField(default=3, verbose_name='课程学分')
    course_open_time = models.DateField(auto_now=True, verbose_name='开课时间')

    teacher = models.ForeignKey(to='Teacher', on_delete=models.CASCADE, related_name='teacher', null=True, blank=True)

    class Meta:
        db_table = "db_course"

    def __str__(self):
        return self.name


class Teacher(models.Model):
    name = models.CharField(max_length=32, verbose_name='老师姓名')
    phone = models.CharField(max_length=11, null=True, blank=True, verbose_name='老师手机号')

    class Meta:
        db_table = "db_teacher"

    def __str__(self):
        return self.name


class StudentDetail(models.Model):
    gender_choice = (
        (0, '保密'),
        (1, '男'),
        (2, '女'),
    )
    gender = models.SmallIntegerField(choices=gender_choice, default=0, verbose_name='性别')
    addr = models.CharField(max_length=64, null=True, blank=True, verbose_name='地址详情')
    phone = models.CharField(max_length=11, null=True, blank=True, verbose_name='手机号')

    class Meta:
        db_table = "db_student_detail"


class Student2Course(models.Model):
    student = models.ForeignKey(to='Student', on_delete=models.CASCADE)
    course = models.ForeignKey(to='Course', on_delete=models.CASCADE)
    choice_course_time = models.DateTimeField(auto_now_add=True, verbose_name='学生选课时间')

    class Meta:
        db_table = "db_student2course"

teacher/models.py
from django.db import models

# Create your models here.

teacher/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.http import JsonResponse
from django.db import transaction

from student import models
from utils.res import ResponseData


def add(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        try:
            with transaction.atomic():
                models.Teacher.objects.create(name=name, phone=phone)
        except Exception as e:
            print(e)
            print('服务器错误---teacher/add!')
        finally:
            return redirect('base:teacher')

    return render(request, 'teacher/add.html')


def edit(request, current_pk):
    teacher_obj = models.Teacher.objects.filter(pk=current_pk).first()
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        models.Teacher.objects.filter(pk=current_pk).update(name=name, phone=phone)
        return redirect('base:teacher')
    return render(request, 'teacher/edit.html', {'teacher_obj': teacher_obj})

def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

def dels(request):
    if is_ajax(request):
        if request.method == 'POST':
            res_dict = ResponseData()
            current_pk = request.POST.get('current_pk')
            try:
                models.Teacher.objects.filter(pk=current_pk).delete()
            except Exception as e:
                res_dict.status = 5000
                res_dict.message = '服务器错误---teacher/dels!'
                print(e)
                print(res_dict.message)
            finally:
                return JsonResponse(res_dict.get_dict)

templates/teacher/add.html
{% extends 'base/index.html' %}

{% block title %}
    <title>teacher-add</title>
{% endblock title %}

{% block content %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="panel-title">添加</div>
        </div>
        <div class="panel-body">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name">老师姓名: </label>
                    <input type="text" id="id_name" name="name" class="form-control">
                </div>
                <div class="form-group">
                    <label for="id_phone">老师手机号: </label>
                    <input type="text" id="id_phone" name="phone" class="form-control">
                </div>
                <input type="submit" class="btn btn-danger" value="确认添加">
                <a href="{% url 'base:teacher' %}" class="btn btn-primary">取消添加</a>
            </form>
        </div>
    </div>
{% endblock content %}

templates/teacher/edit.html
{% extends 'base/index.html' %}

{% block title %}
    <title>teacher-edit</title>
{% endblock title %}

{% block content %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="panel-title">修改</div>
        </div>
        <div class="panel-body">
            <form action="" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name">老师名称: </label>
                    <input type="text" id="id_name" name="name" value="{{ teacher_obj.name }}" class="form-control">
                </div>
                <div class="form-group">
                    <label for="id_phone">老师手机号: </label>
                    <input type="text" id="id_phone" name="phone" value="{{ teacher_obj.phone }}" class="form-control">
                </div>

                <input type="submit" class="btn btn-danger" value="确认修改">
                <a href="{% url 'base:classes' %}" class="btn btn-primary">取消修改</a>
            </form>
        </div>
    </div>
{% endblock content %}